name: Build Fabric
on:
  push:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        clean: false
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Compile
      run: ./gradlew build
    - name: Upload compiled artifacts
      uses: actions/upload-artifact@v4
      with:
        name: celestialwynn
        path: build/libs/*.jar
